apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: eks-enterprise
  source:
    repoURL: https://github.com/DigiWorldfk/aws-eks-enterprise-platform.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: service
          value: frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
