###############################################################################
# ExternalSecret — pulls backend secrets from SSM Parameter Store
###############################################################################

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: backend
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /eks-enterprise-prod/prod/db-password  # REPLACE_WITH_NAME_PREFIX
    - secretKey: JWT_SECRET
      remoteRef:
        key: /eks-enterprise-prod/prod/jwt-secret
    - secretKey: API_KEY
      remoteRef:
        key: /eks-enterprise-prod/prod/api-key
