## Dev overrides
frontend:
  replicaCount: 1
  image:
    tag: develop
  resources:
    limits:
      cpu: 250m
      memory: 256Mi

backend:
  replicaCount: 1
  image:
    tag: develop
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    maxReplicas: 5
